[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "dist/functions"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 